### ISSUE TITLE
git-imerge fails: unable to create directory for .git/logs/refs/heads/imerge/slaveinfo

### ISSUE THREAD

**Issue by jaredgrubb** [mhagger/git-imerge#41]
I'm getting the following error when I tried to use imerge to resolve a merge conflict. I've pushed the two branches (imerge-master and imerge-branch) to my buildbot fork (https://github.com/jaredgrubb/buildbot.git)

```
$ git checkout imerge-master
$ git imerge start --goal rebase --name slaveinfo --first-parent imerge-branch
 [ ... lots of stuff ... ]
Autofilling 4-5 (first way)...success.
Autofilling 4-5 (second way)...success.
The two ways of autofilling 4-5 agree.
Recording autofilled block MergeState('slaveinfo', goal='rebase')[0:5,1:6].
Attempting automerge of 5-2...failure.
error: unable to create directory for .git/logs/refs/heads/imerge/slaveinfo
fatal: Cannot update the ref 'refs/heads/imerge/slaveinfo'.
Traceback (most recent call last):
  File "/Users/jaredgrubb/bin/git-imerge", line 2796, in <module>
    main(sys.argv[1:])
  File "/Users/jaredgrubb/bin/git-imerge", line 222, in wrapper
    return f(*args, **kw)
  File "/Users/jaredgrubb/bin/git-imerge", line 2673, in main
    request_user_merge(merge_state, e.i1, e.i2)
  File "/Users/jaredgrubb/bin/git-imerge", line 2269, in request_user_merge
    refname, above.sha1,
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'update-ref', '-m', "imerge 'slaveinfo': Prepare merge 5-2", 'refs/heads/imerge/slaveinfo', '5dea1f793b2eb0fd2b01c662f0d5a93594ed3e4e']' returned non-zero exit status 128
```

**Comment by mhagger** [comment]
This might have happened because there was already a branch called `refs/heads/imerge` or perhaps `refs/heads/imerge/slaveinfo/FOO`, and the reflog file for that branch blocked the creation of the reflog file for branch `refs/heads/imerge/slaveinfo`. Or perhaps there was a lower-level issue, like a permissions problem within the `.git` directory.

Either way, this is unlikely to be a problem in git-imerge -> closing.
