### ISSUE TITLE
git-imerge fails when merging

### ISSUE THREAD

**Issue by spetsnaz84** [mhagger/git-imerge#70]
I get following trace...:

> git-imerge continue                                                                                                                                    0
[imerge/feature/coresplit 74fb99b] imerge 'feature/coresplit': manual merge 6-1
Merge has been recorded for merge 6-1.
Attempting automerge of 6-2...success.
Attempting automerge of 6-4...success.
Autofilling 6-2...success.
Autofilling 6-3...success.
Autofilling 6-4...success.
Recording autofilled block MergeState('feature/coresplit', tip1='tmp', tip2='feature/coresplit', goal='merge')[5:7,1:5].
Attempting automerge of 7-1...Traceback (most recent call last):
  File "/home/users/myuser/bin/git-imerge", line 3260, in <module>
    main(sys.argv[1:])
  File "/home/users/myuser/bin/git-imerge", line 136, in wrapper
    return f(*args, **kw)
  File "/home/users/myuser/bin/git-imerge", line 3157, in main
    merge_state.auto_complete_frontier()
  File "/home/users/myuser/bin/git-imerge", line 2198, in auto_complete_frontier
    frontier.auto_expand()
  File "/home/users/myuser/bin/git-imerge", line 1353, in auto_expand
    if block.auto_expand_frontier():
  File "/home/users/myuser/bin/git-imerge", line 1651, in auto_expand_frontier
    return self.auto_outline_frontier()
  File "/home/users/myuser/bin/git-imerge", line 1621, in auto_outline_frontier
    merge_frontier = MergeFrontier.compute_by_bisection(self)
  File "/home/users/myuser/bin/git-imerge", line 910, in compute_by_bisection
    if not block.is_mergeable(1, 1):
  File "/home/users/myuser/bin/git-imerge", line 1504, in is_mergeable
    automerge(self[i1, 0].sha1, self[0, i2].sha1)
  File "/home/users/myuser/bin/git-imerge", line 600, in automerge
    call_silently(['git', 'reset', '--merge'])
  File "/home/users/myuser/bin/git-imerge", line 230, in call_silently
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'git', u'reset', u'--merge']' returned non-zero exit status 128

**Comment by mhagger** [comment]
I wonder why `git reset --merge` didn't work. If anybody sees this again, it would be helpful to see the result of running that command manually, and the result of `git status`. Otherwise, it's hard to investigate this any further.
